# Date and Time Variables

#### If we have a column that has dates in it (23 Aug 2012) we can extract a lot of details from it such as: Day, Month, Year, Day of month, Quarter, Semester, Weekday/Weekend

In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [ ]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with dates

In [7]:
# converting to datetime object type
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1. Extract year

In [10]:
date['date_year'] = date['date'].dt.year

date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

## 2. Extract month

In [11]:
date['date_month'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

## 3. Extract Day

In [12]:
date['date_day'] = date['date'].dt.day

date.head()

        date  product_id  city_id  orders  date_year  date_month  date_day
0 2019-12-10        5628       25       3       2019          12        10
1 2018-08-15        3646       14     157       2018           8        15
2 2018-10-23        1859       25       1       2018          10        23
3 2019-08-17        7292       25       1       2019           8        17
4 2019-01-06        4344       25       3       2019           1         6

## 4. Day of week

In [15]:
# Monday is 0th index

date['date_dow'] = date['date'].dt.day_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,10,Tuesday
1,2018-08-15,3646,14,157,2018,8,15,Wednesday
2,2018-10-23,1859,25,1,2018,10,23,Tuesday
3,2019-08-17,7292,25,1,2019,8,17,Saturday
4,2019-01-06,4344,25,3,2019,1,6,Sunday

## 5. Day is a weekend?

In [19]:
date['date_is_weekend'] = np.where(date['date_dow'].isin(['Saturday', 'Sunday']), 1,0)

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_dow,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,10,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,15,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,23,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,17,Saturday,1
4,2019-01-06,4344,25,3,2019,1,6,Sunday,1

## 6. Extract week of the year

In [21]:
date['date_week'] = date['date'].dt.isocalendar().week

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_dow,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,10,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,15,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,23,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,17,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,6,Sunday,1,1

## 7. Extract time elapsed between dates

In [22]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 16, 21, 28, 58, 55488)

In [23]:
today - date['date']

0     2410 days 21:28:58.055488
1     2892 days 21:28:58.055488
2     2823 days 21:28:58.055488
3     2525 days 21:28:58.055488
4     2748 days 21:28:58.055488
                 ...
995   2838 days 21:28:58.055488
996   2779 days 21:28:58.055488
997   2627 days 21:28:58.055488
998   2692 days 21:28:58.055488
999   2466 days 21:28:58.055488
Name: date, Length: 1000, dtype: timedelta64[ns]

In [24]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [25]:
# convert date to datetime object

time['date'] = pd.to_datetime(time['date'])

In [26]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0